### ISSUE TITLE
CSS flex属性包含哪些内容，分别的作用是什么

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/interview#584]
CSS 中的 `flex` 属性其实是指 `flex-grow`、`flex-shrink` 和 `flex-basis` 这三个子属性的缩写。它们分别控制了伸缩元素在容器中的伸缩比例、收缩比例和初始大小。

### flex-grow

控制伸缩元素在空间分配时的增长比例。默认值为 `0`，表示不会增长，当设置为正整数时，伸缩元素会相对于其他伸缩元素按照比例增长，即占据剩余空间的比例。

``` css
.item {
    flex-grow: 1; /* 伸缩元素相对于其他伸缩元素增长的比例 */
}
```

### flex-shrink

控制伸缩元素在空间不足时的收缩比例。默认值为 `1`，表示会按照比例收缩，设置为 `0` 则表示不会收缩。

``` css
.item {
    flex-shrink: 0; /* 伸缩元素不会收缩 */
}
```

### flex-basis
定义了伸缩元素的初始大小。默认值为 `auto`，根据元素的内容大小自动决定大小，也可以设置为固定长度或百分比等值。

``` css
.item {
    flex-basis: 100px; /* 伸缩元素的初始大小为 100px */
}
```

这些属性通常在一个 `flex` 缩写中一起使用，例如：

``` css
.item {
    flex: 1 0 auto;
}
```

上述代码表示伸缩元素会相对于其他伸缩元素按照比例增长，不会收缩，初始大小由内容决定。 `flex` 缩写属性的顺序为 `flex-grow`、`flex-shrink` 和 `flex-basis`。
